# Generated by Django 5.2.1 on 2025-06-29 14:28

import applications.utils.validations
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_cargo_alter_doctor_curriculum_and_more'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre del Empleado')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido del Empleado')),
                ('cedula_ecuatoriana', models.CharField(help_text='Ingrese el número de cédula sin espacios ni guiones.', max_length=10, validators=[applications.utils.validations.valida_cedula], verbose_name='Cédula')),
                ('dni', models.CharField(blank=True, help_text='Pasaporte, DNI, CURP u otro documento válido internacionalmente.', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un documento válido (letras, números, guiones o puntos).', regex='^[A-Za-z0-9\\-\\. ]{5,30}$')], verbose_name='DNI Internacional')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='core/empleados/', verbose_name='Foto del Empleado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='doctor.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
