# Generated by Django 5.0.7 on 2025-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.CharField(help_text='Ubicación física donde atiende el doctor.', max_length=255, verbose_name='Dirección de Trabajo'),
        ),
    ]
