# Generated by Django 5.2.1 on 2025-06-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: Médico, Enfermero, Administrador', max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del rol que cumple este cargo (opcional).', null=True, verbose_name='Descripción del Cargo')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva este cargo si ya no se usa en el sistema.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='curriculum',
            field=models.FileField(blank=True, help_text='Archivo PDF o DOC (opcional).', null=True, upload_to='applications/curriculums/', verbose_name='Currículum Vitae'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='firma_digital',
            field=models.ImageField(blank=True, help_text='Imagen que será usada para firmar digitalmente.', null=True, upload_to='applications/firmas/', verbose_name='Firma Digital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='imagen_receta',
            field=models.ImageField(blank=True, help_text='Encabezado o firma que se mostrará en recetas médicas.', null=True, upload_to='applications/recetas/', verbose_name='Imagen para Recetas'),
        ),
    ]
