# Generated by Django 5.2.1 on 2025-06-28 15:12

import applications.pacientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='10 dígitos sin espacios ni guiones.', max_length=10, validators=[applications.pacientes.models.valida_cedula], verbose_name='Cédula ecuatoriana')),
                ('dni', models.CharField(blank=True, help_text='Opcional: pasaporte, DNI, CURP, etc.', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Debe ser pasaporte, DNI, CURP u otro válido.', regex='^[A-Za-z0-9\\-\\. ]{5,30}$')], verbose_name='DNI internacional')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo')),
                ('phone', models.CharField(blank=True, help_text='Puede separar varios con comas.', max_length=50, null=True, verbose_name='Teléfono(s)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de sangre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
