# Generated by Django 5.0.7 on 2025-06-29 04:39

import applications.pacientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes familiares'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedentes_gineco_obstetricos',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes gineco-obstétricos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedentes_personales',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes personales patológicos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedentes_quirurgicos',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes quirúrgicos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('U', 'Unido')], default='S', max_length=12, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/pacientes/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='patient',
            name='habitos_toxicos',
            field=models.CharField(default='ninguno', max_length=200, verbose_name='Hábitos tóxicos o perjudiciales'),
        ),
        migrations.AddField(
            model_name='patient',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos actuales'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vacunas',
            field=models.TextField(blank=True, null=True, verbose_name='Vacunas'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[applications.pacientes.models.valida_cedula], verbose_name='Cédula ecuatoriana'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-\\. ]{5,30}$', 'Debe ser pasaporte, DNI, CURP u otro válido.')], verbose_name='DNI internacional'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono(s)'),
        ),
    ]
