# Generated by Django 5.0.7 on 2025-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_patient_estado_civil_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='applications/pacientes/', verbose_name='Foto'),
        ),
    ]
